**a)  Creating random vector of size 15 having only Integers in the range 1-20.**

In [1]:

import numpy as np
v =  np.random.randint(1,20,(15,))

# Reshaping the array to 3 by 5
arr = v.reshape(3,5)
print(arr.shape)
print(arr)

# Replacing the max in each row by 0
row_max = arr.max(axis=1).reshape(-1,1)
arr = np.where(arr == row_max, 0, arr)
print('\n',arr)


(3, 5)
[[10 10 18  8  6]
 [ 1 18  7  4 12]
 [15 11 18  8 15]]

 [[10 10  0  8  6]
 [ 1  0  7  4 12]
 [15 11  0  8 15]]


** Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array**

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 5, 7]], np.int32)
print('Shape:', x.shape)
print('Type:', type(x))
print('Data type:', x.dtype)


Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


**b)Computing the eigenvalues and right eigenvectors**

In [3]:
from numpy import linalg as LA
mat = np.array([[3, -2], [1, 0]], np.int32)
w, v = LA.eig(mat)
print('Eigenvalues:', w)
print('\nRight eigenvectors:\n', v)


Eigenvalues: [2. 1.]

Right eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


**c) Computing the sum of the diagonal element**

In [4]:
n = np.array([[0, 1, 2], [3, 4, 5]])
res = np.trace
print('Sum of diagonal elements:', res)


Sum of diagonal elements: <function trace at 0x783e9cfe52d0>


**d) Write a NumPy program to create a new shape to an array without changing its data.**

In [7]:
m = np.arange(1,7).reshape(3,2)
m = m.reshape(2,3)
m


array([[1, 2, 3],
       [4, 5, 6]])